AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: POC for dynamo and open search integration

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    MemorySize: 256
    CodeUri: .
    Architectures:
      - x86_64
    Runtime: nodejs20.x
  Api:
    TracingEnabled: true

Resources:
  ##########################################################################
  #                             Dynamo                                     #
  ##########################################################################
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dynamo-table
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: rangeN1
          AttributeType: N
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: rangeN1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
            

  ##########################################################################
  #                             OpenSearch Cluster                         #
  ##########################################################################
#  OpenSearchDomain:
#    Type: AWS::OpenSearchService::Domain
#    Properties:
#      DomainName: open-search-domain

  ##########################################################################
  #                              REST API Gateway                          #
  ##########################################################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Description: API
      StageName: dev

  ##########################################################################
  #                              Layers                                    #
  ##########################################################################
  DepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: depsLayer
      Description: Dependencies layer
      ContentUri: ./layers/deps
      CompatibleRuntimes:
        - nodejs20.x
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs20.x
      BuildArchitecture: x86_64

  ##########################################################################
  #                              Lambdas                                   #
  ##########################################################################

  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: api-lambda
      Handler: api-handler.apiHandler
      Layers:
        - !Ref DepsLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        LibraryEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /library
            Method: ANY
        BookEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /book
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - AWSLambdaExecute
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
          DYNAMO_TABLE: !Ref DynamoDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambdas/api-handler.ts
        External:
          - zod
          - dayjs
          - ksuid
          - fastify
          - "@fastify/aws-lambda"
          - "@fastify/jwt"
          - "@aws-sdk/client-dynamodb"
##########################################################################
#                                 Outputs                                #
##########################################################################
Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
  ApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"